INSERT INTO TB_CALCULADORA(PRIMEIRO_VALOR, SEGUNDO_VALOR, VALOR_TOTAL, TIPO_CALCULO, DATA_CADASTRO) VALUES (20.00, 20.00, 40.00, 'SOMA', NOW());
INSERT INTO TB_CALCULADORA(PRIMEIRO_VALOR, SEGUNDO_VALOR, VALOR_TOTAL, TIPO_CALCULO, DATA_CADASTRO) VALUES (20.00, 20.00, 0.00, 'SUBTRACAO', NOW());
INSERT INTO TB_CALCULADORA(PRIMEIRO_VALOR, SEGUNDO_VALOR, VALOR_TOTAL, TIPO_CALCULO, DATA_CADASTRO) VALUES (20.00, 20.00, 1.00, 'DIVISAO', NOW());
INSERT INTO TB_CALCULADORA(PRIMEIRO_VALOR, SEGUNDO_VALOR, VALOR_TOTAL, TIPO_CALCULO, DATA_CADASTRO) VALUES (30.00, 20.00, 60.00, 'MULTIPLICACAO', NOW());