create table TB_CALCULADORA(
   ID bigserial primary key,
   PRIMEIRO_VALOR NUMERIC(10,2) not null,
   SEGUNDO_VALOR NUMERIC(10,2) not null,
   VALOR_TOTAL NUMERIC(10,2) not null,
   TIPO_CALCULO varchar(255) not null,
   DATA_CADASTRO TIMESTAMP not null,
   DATA_ATUALIZACAO TIMESTAMP
);

ALTER TABLE TB_CALCULADORA ADD CONSTRAINT CK_TIPO_CALCULO check (TIPO_CALCULO in ('SOMA','SUBTRACAO', 'MULTIPLICACAO', 'DIVISAO'));
ALTER TABLE TB_CALCULADORA ALTER COLUMN DATA_CADASTRO SET DEFAULT current_timestamp AT TIME ZONE 'UTC';
ALTER TABLE TB_CALCULADORA ALTER COLUMN DATA_ATUALIZACAO SET DEFAULT current_timestamp AT TIME ZONE 'UTC';